/*
 * ============================================================================
 * Copyright (c) 2013   Marvell International, Ltd. All Rights Reserved
 *
 *                         Marvell Confidential
 * ============================================================================
 */

/** 
 * \file ui_system_interface_status.c
 * 
 * \brief Implementations of status table and shared status routines for UI 
 *        System Interface.
 *        
 * 
 **/

#include <string.h>
#include "ui_system_interface_api.h"
#include "ui_system_interface_status.h"

#ifdef HAVE_COMMON_CONSUMABLES_API
#include "ui_system_interface_consumables.h"
#endif

#ifdef HAVE_PLATFORM
#include "ui_system_interface_platform.h"
#endif

#ifdef HAVE_PRINT_SUPPORT
#include "ui_system_interface_print.h"
#endif

#ifdef HAVE_SCAN_SUPPORT
#include "ui_system_interface_scan.h"
#endif

#ifdef HAVE_COPY_SUPPORT
#include "ui_system_interface_copy.h"
#endif

#ifdef HAVE_NETWORK
#include "ui_system_interface_network.h"
#endif

#ifdef HAVE_FAX_SUPPORT
#include "ui_system_interface_fax.h"
#endif

#include "logger.h"

// string representation for the types of status messages
// NOTE: this list must match up with the MSG_TYPE_TAG enum
const char *msg_type_strings[NUM_MSG_TYPES_PLUS_ONE] =
{
    "UNUSED",
    "MSG_READY",
    "MSG_JOB",
    "MSG_CONFIRM_PROMPT",
    "MSG_TRANSITORY",
    "MSG_ALERT",
    "MSG_WARN",
    "MSG_NOTIFY",
    "MSG_ANNOUNCE",
    "MSG_FATAL"
};

const char *status_type_to_string(MSG_TYPE cur_type)
{
    return msg_type_strings[cur_type];
}

// table of module-specific supported status'
static StatMsg DispStatusMessage[] = 
{
    {MSG_READY,          UI_SYS_STATSEV_NONE      | UI_SYS_STATPRI_0, SYSTEM_MODULE_NAME, SYSTEM_STATUS_IDLE},
#ifdef HAVE_PLATFORM
    {MSG_READY,          UI_SYS_STATSEV_NONE      | UI_SYS_STATPRI_0, PLATFORM_MODULE_NAME, PLATFORM_STATUS_IDLE},
#endif
#ifdef HAVE_PRINT_SUPPORT
    {MSG_READY,          UI_SYS_STATSEV_NONE      | UI_SYS_STATPRI_0, PRINT_MODULE_NAME, PRINT_STATUS_IDLE},
#endif
#ifdef HAVE_COMMON_CONSUMABLES_API
    {MSG_READY,          UI_SYS_STATSEV_NONE      | UI_SYS_STATPRI_0, CONSUMABLES_MODULE_NAME, CONSUMABLES_STATUS_IDLE},
#endif
#ifdef HAVE_SCAN_SUPPORT
    {MSG_READY,          UI_SYS_STATSEV_NONE      | UI_SYS_STATPRI_0, SCAN_MODULE_NAME, SCAN_STATUS_IDLE},
    {MSG_READY,          UI_SYS_STATSEV_NONE      | UI_SYS_STATPRI_0, CONTINUOUSSCAN_MODULE_NAME, CONTINUOUSSCAN_STATUS_IDLE},
#endif // #ifdef HAVE_SCAN_SUPPORT
#ifdef HAVE_COPY_SUPPORT
    {MSG_READY,          UI_SYS_STATSEV_NONE      | UI_SYS_STATPRI_0, COPY_MODULE_NAME, COPY_STATUS_IDLE},
    {MSG_READY,          UI_SYS_STATSEV_NONE      | UI_SYS_STATPRI_0, IDCOPY_MODULE_NAME, IDCOPY_STATUS_IDLE},
    {MSG_READY,          UI_SYS_STATSEV_NONE      | UI_SYS_STATPRI_0, CONTINUOUSCOPY_MODULE_NAME, CONTINUOUSCOPY_STATUS_IDLE},
#endif // #ifdef HAVE_COPY_SUPPORT
#ifdef HAVE_FAX_SUPPORT
    {MSG_READY,          UI_SYS_STATSEV_NONE      | UI_SYS_STATPRI_0, FAX_MODULE_NAME, FAX_STATUS_READY},
    {MSG_READY,          UI_SYS_STATSEV_NONE      | UI_SYS_STATPRI_0, FAXSCAN_MODULE_NAME, FAX_SCAN_STATUS_READY},
    {MSG_READY,          UI_SYS_STATSEV_NONE      | UI_SYS_STATPRI_0, FAXPRINT_MODULE_NAME, FAX_PRINT_STATUS_READY},
#endif // #ifdef HAVE_FAX_SUPPORT
#ifdef HAVE_WIRELESS
    {MSG_READY,          UI_SYS_STATSEV_NONE      | UI_SYS_STATPRI_0, WIFI_MODULE_NAME, WIFI_STATUS_READY},
    {MSG_READY,          UI_SYS_STATSEV_NONE      | UI_SYS_STATPRI_0, WPS_MODULE_NAME, WPS_STATUS_IDLE},
#endif // #ifdef HAVE_WIRELESS

#ifdef HAVE_UI_SYSTEM_INTERFACE_OEM
    // include the supported OEM-specific status messages
    #include "ui_system_interface_oem_status.h"
#endif // #ifdef HAVE_UI_SYSTEM_INTERFACE_OEM

#ifdef HAVE_PLATFORM
    {MSG_JOB,            UI_SYS_STATSEV_INFO      | UI_SYS_STATPRI_0, PLATFORM_MODULE_NAME, PLATFORM_STATUS_BURNFLASH_PROGRAMMING},
    {MSG_JOB,            UI_SYS_STATSEV_INFO      | UI_SYS_STATPRI_0, PLATFORM_MODULE_NAME, PLATFORM_STATUS_BURNFLASH_COMPLETE},
#endif

#ifdef HAVE_PRINT_SUPPORT
    {MSG_JOB,            UI_SYS_STATSEV_INFO      | UI_SYS_STATPRI_0, PRINT_MODULE_NAME, PRINT_STATUS_PRINTING},
    {MSG_JOB,            UI_SYS_STATSEV_INFO_HIGH | UI_SYS_STATPRI_1, PRINT_MODULE_NAME, PRINT_STATUS_CANCELING},
    {MSG_JOB,            UI_SYS_STATSEV_CRITICAL  | UI_SYS_STATPRI_1, PRINT_MODULE_NAME, PRINT_STATUS_INITIALIZING},
    {MSG_JOB,            UI_SYS_STATSEV_INFO      | UI_SYS_STATPRI_0, PRINT_MODULE_NAME, PRINT_STATUS_CLEANING},
    {MSG_NOTIFY,         UI_SYS_STATSEV_CRITICAL  | UI_SYS_STATPRI_1, PRINT_MODULE_NAME, PRINT_STATUS_INTERNAL_CLEANING},
    {MSG_NOTIFY,         UI_SYS_STATSEV_CRITICAL  | UI_SYS_STATPRI_1, PRINT_MODULE_NAME, PRINT_STATUS_MEASURING_TONER},
    {MSG_CONFIRM_PROMPT, UI_SYS_STATSEV_CRITICAL  | UI_SYS_STATPRI_1, PRINT_MODULE_NAME, PRINT_STATUS_PAPER_OUT},
    {MSG_CONFIRM_PROMPT, UI_SYS_STATSEV_WARNING   | UI_SYS_STATPRI_1, PRINT_MODULE_NAME, PRINT_STATUS_PAPER_OUT_ALL},
    {MSG_CONFIRM_PROMPT, UI_SYS_STATSEV_CRITICAL  | UI_SYS_STATPRI_1, PRINT_MODULE_NAME, PRINT_STATUS_MANUAL_DUPLEX},
    {MSG_ALERT,          UI_SYS_STATSEV_CRITICAL  | UI_SYS_STATPRI_2, PRINT_MODULE_NAME, PRINT_STATUS_DOOR_OPEN},
    {MSG_ALERT,          UI_SYS_STATSEV_CRITICAL  | UI_SYS_STATPRI_2, PRINT_MODULE_NAME, PRINT_STATUS_REAR_DOOR_OPEN},
    {MSG_ALERT,          UI_SYS_STATSEV_CRITICAL  | UI_SYS_STATPRI_1, PRINT_MODULE_NAME, PRINT_STATUS_PAPER_JAM},
    {MSG_ALERT,          UI_SYS_STATSEV_CRITICAL  | UI_SYS_STATPRI_1, PRINT_MODULE_NAME, PRINT_STATUS_PAPER_JAM_INPUT},
    {MSG_ALERT,          UI_SYS_STATSEV_CRITICAL  | UI_SYS_STATPRI_1, PRINT_MODULE_NAME, PRINT_STATUS_PAPER_JAM_OUTPUT},
    {MSG_ALERT,          UI_SYS_STATSEV_CRITICAL  | UI_SYS_STATPRI_1, PRINT_MODULE_NAME, PRINT_STATUS_CART_MISSING},
#endif

#ifdef HAVE_SCAN_SUPPORT
    {MSG_JOB,            UI_SYS_STATSEV_CRITICAL  | UI_SYS_STATPRI_1, SCAN_MODULE_NAME, SCAN_STATUS_INITIALIZING},
    {MSG_JOB,            UI_SYS_STATSEV_INFO      | UI_SYS_STATPRI_0, SCAN_MODULE_NAME, SCAN_STATUS_RUNNING},
    {MSG_JOB,            UI_SYS_STATSEV_INFO      | UI_SYS_STATPRI_0, SCAN_MODULE_NAME, SCAN_STATUS_CALBRATING},
    {MSG_JOB,            UI_SYS_STATSEV_CRITICAL  | UI_SYS_STATPRI_0, SCAN_MODULE_NAME, SCAN_STATUS_CANCELING},
    {MSG_ALERT,          UI_SYS_STATSEV_CRITICAL  | UI_SYS_STATPRI_1, SCAN_MODULE_NAME, SCAN_STATUS_OFFLINE},
    {MSG_ALERT,          UI_SYS_STATSEV_CRITICAL  | UI_SYS_STATPRI_3, SCAN_MODULE_NAME, SCAN_STATUS_PAPER_NOPICK},
    {MSG_ALERT,          UI_SYS_STATSEV_CRITICAL  | UI_SYS_STATPRI_3, SCAN_MODULE_NAME, SCAN_STATUS_PAPER_JAM},
    {MSG_JOB,            UI_SYS_STATSEV_INFO      | UI_SYS_STATPRI_0, CONTINUOUSSCAN_MODULE_NAME, COPY_SCAN_STATUS_RUNNING},
#endif // #ifdef HAVE_SCAN_SUPPORT

#ifdef HAVE_COPY_SUPPORT
    {MSG_JOB,            UI_SYS_STATSEV_INFO_HIGH | UI_SYS_STATPRI_1, COPY_MODULE_NAME, COPY_STATUS_CANCELING},
    {MSG_JOB,            UI_SYS_STATSEV_INFO_HIGH | UI_SYS_STATPRI_1, IDCOPY_MODULE_NAME, COPY_STATUS_CANCELING},
    {MSG_CONFIRM_PROMPT, UI_SYS_STATSEV_CRITICAL  | UI_SYS_STATPRI_1, COPY_MODULE_NAME, COPY_STATUS_USER_INPUT},
    {MSG_TRANSITORY,     UI_SYS_STATSEV_INFO_HIGH | UI_SYS_STATPRI_0, SYSTEM_MODULE_NAME, COPY_STATUS_BUSY},
    {MSG_TRANSITORY,     UI_SYS_STATSEV_INFO_HIGH | UI_SYS_STATPRI_0, SYSTEM_MODULE_NAME, COPY_STATUS_PENDING},
    {MSG_JOB,            UI_SYS_STATSEV_INFO      | UI_SYS_STATPRI_0, COPY_MODULE_NAME, COPY_STATUS_PAGECOUNT},
    {MSG_JOB,            UI_SYS_STATSEV_INFO      | UI_SYS_STATPRI_0, IDCOPY_MODULE_NAME, COPY_STATUS_PAGECOUNT},
    {MSG_JOB,            UI_SYS_STATSEV_INFO      | UI_SYS_STATPRI_0, CONTINUOUSCOPY_MODULE_NAME, COPY_STATUS_PAGECOUNT},
    {MSG_CONFIRM_PROMPT, UI_SYS_STATSEV_CRITICAL  | UI_SYS_STATPRI_1, IDCOPY_MODULE_NAME, COPY_STATUS_USER_INPUT},
#endif // #ifdef HAVE_COPY_SUPPORT

#ifdef HAVE_FAX_SUPPORT
    {MSG_CONFIRM_PROMPT, UI_SYS_STATSEV_CRITICAL  | UI_SYS_STATPRI_1, FAXSCAN_MODULE_NAME, FAX_SCAN_STATUS_PROMPT_MORE},
    {MSG_CONFIRM_PROMPT, UI_SYS_STATSEV_CRITICAL  | UI_SYS_STATPRI_1, FAXSCAN_MODULE_NAME, FAX_SCAN_STATUS_LOADPAGE},
    {MSG_JOB,            UI_SYS_STATSEV_INFO      | UI_SYS_STATPRI_2, FAXSCAN_MODULE_NAME, FAX_SCAN_STATUS_STORING},
    {MSG_JOB,            UI_SYS_STATSEV_INFO      | UI_SYS_STATPRI_3, FAX_MODULE_NAME, FAX_STATUS_DIALING},
    {MSG_JOB,            UI_SYS_STATSEV_INFO      | UI_SYS_STATPRI_2, FAX_MODULE_NAME, FAX_STATUS_CONNECTING},
    {MSG_JOB,            UI_SYS_STATSEV_INFO      | UI_SYS_STATPRI_3, FAX_MODULE_NAME, FAX_STATUS_SENDING},
    {MSG_TRANSITORY,     UI_SYS_STATSEV_INFO      | UI_SYS_STATPRI_3, FAX_MODULE_NAME, FAX_RESULT_SENT_OK},
    {MSG_TRANSITORY,     UI_SYS_STATSEV_INFO      | UI_SYS_STATPRI_3, FAX_MODULE_NAME, FAX_RESULT_SENT_RTN},
    {MSG_TRANSITORY,     UI_SYS_STATSEV_INFO      | UI_SYS_STATPRI_3, FAX_MODULE_NAME, FAX_RESULT_SENT_PARTIAL},
    {MSG_JOB,            UI_SYS_STATSEV_CRITICAL  | UI_SYS_STATPRI_3, FAX_MODULE_NAME, FAX_STATUS_INCOMING_CALL},
    {MSG_JOB,            UI_SYS_STATSEV_INFO      | UI_SYS_STATPRI_3, FAX_MODULE_NAME, FAX_STATUS_RECEIVING},
    {MSG_TRANSITORY,     UI_SYS_STATSEV_INFO      | UI_SYS_STATPRI_3, FAX_MODULE_NAME, FAX_RESULT_BLOCKED},
    {MSG_TRANSITORY,     UI_SYS_STATSEV_INFO      | UI_SYS_STATPRI_3, FAX_MODULE_NAME, FAX_RESULT_RCVD_OK},
    {MSG_TRANSITORY,     UI_SYS_STATSEV_INFO      | UI_SYS_STATPRI_3, FAX_MODULE_NAME, FAX_RESULT_RCVD_RTN},
    {MSG_TRANSITORY,     UI_SYS_STATSEV_INFO      | UI_SYS_STATPRI_3, FAX_MODULE_NAME, FAX_RESULT_RCVD_PARTIAL},
    {MSG_TRANSITORY,     UI_SYS_STATSEV_INFO      | UI_SYS_STATPRI_3, FAX_MODULE_NAME, FAX_RESULT_NO_DIAL_TONE},
    {MSG_TRANSITORY,     UI_SYS_STATSEV_INFO      | UI_SYS_STATPRI_3, FAX_MODULE_NAME, FAX_RESULT_COMM_ERROR},
    {MSG_TRANSITORY,     UI_SYS_STATSEV_INFO      | UI_SYS_STATPRI_3, FAX_MODULE_NAME, FAX_STATUS_CANCELING_RECV},
    {MSG_TRANSITORY,     UI_SYS_STATSEV_INFO      | UI_SYS_STATPRI_3, FAX_MODULE_NAME, FAX_STATUS_CANCELING_SEND},
    {MSG_JOB       ,     UI_SYS_STATSEV_INFO      | UI_SYS_STATPRI_3, FAXSCAN_MODULE_NAME, FAX_SCAN_STATUS_CANCELING},
    {MSG_TRANSITORY,     UI_SYS_STATSEV_INFO      | UI_SYS_STATPRI_3, FAXSCAN_MODULE_NAME, FAX_RESULT_FS_FULL_SEND},
    {MSG_TRANSITORY,     UI_SYS_STATSEV_INFO      | UI_SYS_STATPRI_3, FAXSCAN_MODULE_NAME, FAX_IPAGE_ACTIVITY_LOG},
    {MSG_TRANSITORY,     UI_SYS_STATSEV_INFO      | UI_SYS_STATPRI_3, FAXSCAN_MODULE_NAME, FAX_SCAN_STATUS_JOB_SCHEDULED},
    {MSG_TRANSITORY,     UI_SYS_STATSEV_INFO      | UI_SYS_STATPRI_3, FAXSCAN_MODULE_NAME, FAX_SCAN_STATUS_JOB_ADDED},
    {MSG_TRANSITORY,     UI_SYS_STATSEV_INFO      | UI_SYS_STATPRI_3, FAX_MODULE_NAME, FAX_RESULT_FS_FULL_SEND},
    {MSG_TRANSITORY,     UI_SYS_STATSEV_INFO      | UI_SYS_STATPRI_3, FAX_MODULE_NAME, FAX_RESULT_FS_FULL_RECV},
    {MSG_TRANSITORY,     UI_SYS_STATSEV_INFO      | UI_SYS_STATPRI_3, FAX_MODULE_NAME, FAX_RESULT_FS_ERROR_SEND},
    {MSG_TRANSITORY,     UI_SYS_STATSEV_INFO      | UI_SYS_STATPRI_3, FAX_MODULE_NAME, FAX_RESULT_FS_ERROR_RECV},
    {MSG_JOB,            UI_SYS_STATSEV_INFO      | UI_SYS_STATPRI_0, FAXPRINT_MODULE_NAME, FAX_PRINT_STATUS_PRINTING},
    {MSG_TRANSITORY,     UI_SYS_STATSEV_INFO      | UI_SYS_STATPRI_3, FAX_MODULE_NAME, FAX_RESULT_LINE_BUSY},
    {MSG_TRANSITORY,     UI_SYS_STATSEV_INFO      | UI_SYS_STATPRI_3, FAX_MODULE_NAME, FAX_RESULT_NO_ANSWER},
    {MSG_TRANSITORY,     UI_SYS_STATSEV_INFO      | UI_SYS_STATPRI_3, FAX_MODULE_NAME, FAX_RESULT_NO_FAX_DETECTED},
    {MSG_TRANSITORY,     UI_SYS_STATSEV_INFO      | UI_SYS_STATPRI_3, FAXSCAN_MODULE_NAME, FAX_SCAN_STATUS_SYSTEM_BUSY},
    {MSG_JOB,            UI_SYS_STATSEV_INFO      | UI_SYS_STATPRI_3, FAX_MODULE_NAME, FAX_STATUS_SELF_TEST},
    {MSG_JOB,            UI_SYS_STATSEV_INFO      | UI_SYS_STATPRI_3, FAX_MODULE_NAME, FAX_STATUS_VOICE_CALL},
    {MSG_JOB,            UI_SYS_STATSEV_INFO      | UI_SYS_STATPRI_3, FAX_MODULE_NAME, FAX_STATUS_VOICE_CANCELING},
    {MSG_TRANSITORY,     UI_SYS_STATSEV_INFO_HIGH | UI_SYS_STATPRI_1, FAXPRINT_MODULE_NAME, FAX_PRINT_STATUS_CANCELING},
#endif // #ifdef HAVE_FAX_SUPPORT

#ifdef HAVE_WIRELESS
#ifdef FIXED_UNITY_LINKS
    {MSG_JOB,            UI_SYS_STATSEV_INFO      | UI_SYS_STATPRI_0, WIFI_MODULE_NAME, WIFI_STATUS_SELF_TEST},
#endif // FIXED_UNITY_LINKS
    {MSG_JOB,            UI_SYS_STATSEV_INFO      | UI_SYS_STATPRI_0, WPS_MODULE_NAME, WPS_STATUS_SEARCHING},
    {MSG_JOB,            UI_SYS_STATSEV_INFO      | UI_SYS_STATPRI_0, WPS_MODULE_NAME, WPS_STATUS_CONNECTING},
    {MSG_CONFIRM_PROMPT, UI_SYS_STATSEV_INFO      | UI_SYS_STATPRI_1, WPS_MODULE_NAME, WPS_STATUS_FAILED},
    {MSG_CONFIRM_PROMPT, UI_SYS_STATSEV_INFO      | UI_SYS_STATPRI_1, WPS_MODULE_NAME, WPS_STATUS_SUCCESS},
    {MSG_CONFIRM_PROMPT, UI_SYS_STATSEV_INFO      | UI_SYS_STATPRI_1, WPS_MODULE_NAME, WPS_STATUS_NO_ROUTERS},
    {MSG_JOB,            UI_SYS_STATSEV_INFO_HIGH | UI_SYS_STATPRI_1, WPS_MODULE_NAME, WPS_STATUS_CANCELLED},
#endif // #ifdef HAVE_WIRELESS

    {0, 0, 0, 0}
};


/**\brief Locates the "online" message for a given module.
 * 
 * \param[in] module_name The module whose "online" status is needed.
 * 
 * \return String indicating the status to set for it to be "online"
 */

const char *findOnlineStatusForModule( const char *module_name )
{
    UINT32 TmpIndex = 0;
    const char *RetStatus = NULL;

    if (module_name != NULL)
    {
        while ( DispStatusMessage[ TmpIndex ].msgType)
        {
            if ( ( DispStatusMessage[ TmpIndex ].StatMgrCode == (UI_SYS_STATSEV_NONE|UI_SYS_STATPRI_0) ) &&
                 ( DispStatusMessage[ TmpIndex ].module != NULL ) &&
                 ( strcmp( DispStatusMessage[ TmpIndex ].module, module_name ) == 0 ) )
            {
                // We found the online message for the module.
                RetStatus = DispStatusMessage[ TmpIndex ].state;
                break;
            }

            TmpIndex++;

        }
    }
    return RetStatus;
}


// Utility function to return a pointer to the given module/state entry in the status table.
StatMsg *find_module_state_entry(const char *module, const char *state)
{
    UINT32 tmp_index = 0;
    StatMsg *ret_msg = NULL;

    while ( DispStatusMessage[tmp_index].msgType)
    {
        if (DispStatusMessage[tmp_index].module && !strcmp(DispStatusMessage[tmp_index].module, module) &&
            DispStatusMessage[tmp_index].state  && !strcmp(DispStatusMessage[tmp_index].state, state))
        {
            // found the requested module/state, so return a pointer to it
            ret_msg = &(DispStatusMessage[tmp_index]);
            break;
        }

        tmp_index++;
    }

    if (NULL == ret_msg)
    {
        // warn that the requested module/state isn't supported
        DPRINTF((DBG_LOUD | DBG_OUTPUT), ("%s@%d: Unknown status with module=%s and state=%s\n", __FILE__, __LINE__, module, state));
    }

    return ret_msg;
}


